import type { ReportTemplate } from '../types';

export const BUILTIN_REPORT_TEMPLATES: readonly ReportTemplate[] = [
  {
    id: 'rt-incident-report',
    name: 'Incident Report',
    description: 'Standard incident report covering timeline, impact, IOCs, and remediation.',
    icon: '🚨',
    category: 'Incident Response',
    sections: [
      { id: 's1', title: 'Executive Summary', order: 0, placeholder: 'One-paragraph summary of the incident, impact, and current status.', entityHints: [] },
      { id: 's2', title: 'Incident Timeline', order: 1, placeholder: 'Chronological sequence of events from initial detection to containment.', entityHints: ['timeline'] },
      { id: 's3', title: 'Affected Systems & Scope', order: 2, placeholder: 'List of affected hosts, networks, accounts, and data categories.', entityHints: ['notes'] },
      { id: 's4', title: 'Indicators of Compromise', order: 3, placeholder: 'IOCs observed during the investigation: IPs, domains, hashes, URLs.', entityHints: ['iocs'] },
      { id: 's5', title: 'Root Cause Analysis', order: 4, placeholder: 'How the attacker gained initial access and what vulnerabilities were exploited.', entityHints: ['notes'] },
      { id: 's6', title: 'Containment & Eradication', order: 5, placeholder: 'Actions taken to stop the attack and remove the threat from the environment.', entityHints: ['tasks'] },
      { id: 's7', title: 'Recommendations', order: 6, placeholder: 'Short-term tactical mitigations and long-term strategic improvements.', entityHints: [] },
      { id: 's8', title: 'Appendix', order: 7, placeholder: 'Supporting evidence, raw logs, or technical artifacts.', entityHints: ['notes'] },
    ],
    source: 'builtin',
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'rt-threat-intel',
    name: 'Threat Intelligence Report',
    description: 'Structured CTI report with actor profile, TTPs, and infrastructure analysis.',
    icon: '🔍',
    category: 'Threat Intelligence',
    sections: [
      { id: 's1', title: 'Key Findings', order: 0, placeholder: 'Three to five bullet points summarizing the most important findings.', entityHints: [] },
      { id: 's2', title: 'Threat Actor Profile', order: 1, placeholder: 'Attribution confidence, known aliases, motivation, and target sectors.', entityHints: ['notes'] },
      { id: 's3', title: 'Campaign Overview', order: 2, placeholder: 'Observed campaign activity, timeframe, and geographic focus.', entityHints: ['timeline'] },
      { id: 's4', title: 'Malware & Tooling', order: 3, placeholder: 'Tools, malware families, and custom implants used in the campaign.', entityHints: ['iocs'] },
      { id: 's5', title: 'MITRE ATT&CK Mapping', order: 4, placeholder: 'Observed techniques mapped to ATT&CK tactics.', entityHints: ['notes'] },
      { id: 's6', title: 'Infrastructure Analysis', order: 5, placeholder: 'C2 infrastructure, hosting providers, and operational patterns.', entityHints: ['iocs', 'graph'] },
      { id: 's7', title: 'Detection Guidance', order: 6, placeholder: 'YARA rules, Sigma rules, network signatures, and behavioral detections.', entityHints: ['notes'] },
      { id: 's8', title: 'Confidence Assessment', order: 7, placeholder: 'Overall confidence in attribution and key judgments with supporting rationale.', entityHints: [] },
    ],
    source: 'builtin',
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'rt-executive-brief',
    name: 'Executive Brief',
    description: 'Short, non-technical brief for leadership covering impact and business risk.',
    icon: '📋',
    category: 'Executive',
    sections: [
      { id: 's1', title: 'Situation', order: 0, placeholder: 'What happened, in plain language. One to two sentences.', entityHints: [] },
      { id: 's2', title: 'Business Impact', order: 1, placeholder: 'What was affected — data, operations, customers, regulatory exposure.', entityHints: ['notes'] },
      { id: 's3', title: 'Current Status', order: 2, placeholder: 'Is the threat contained? What is still at risk?', entityHints: [] },
      { id: 's4', title: 'Actions Taken', order: 3, placeholder: 'What has the security team done so far to respond.', entityHints: ['tasks'] },
      { id: 's5', title: 'Next Steps', order: 4, placeholder: 'Decisions or resources needed from leadership.', entityHints: ['tasks'] },
    ],
    source: 'builtin',
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'rt-vulnerability-assessment',
    name: 'Vulnerability Assessment',
    description: 'Structured vulnerability report with severity ratings and remediation tracking.',
    icon: '🛡️',
    category: 'Vulnerability Management',
    sections: [
      { id: 's1', title: 'Assessment Scope', order: 0, placeholder: 'Systems and applications assessed, assessment methodology, and timeframe.', entityHints: [] },
      { id: 's2', title: 'Critical & High Findings', order: 1, placeholder: 'CVEs and vulnerabilities rated Critical or High with CVSS scores.', entityHints: ['iocs', 'notes'] },
      { id: 's3', title: 'Medium Findings', order: 2, placeholder: 'Medium-severity vulnerabilities.', entityHints: ['notes'] },
      { id: 's4', title: 'Remediation Plan', order: 3, placeholder: 'Prioritized remediation steps with owners and target dates.', entityHints: ['tasks'] },
      { id: 's5', title: 'Metrics', order: 4, placeholder: 'Total vulnerabilities by severity, mean time to patch, patch coverage.', entityHints: [] },
    ],
    source: 'builtin',
    createdAt: 0,
    updatedAt: 0,
  },
];
