// src/lib/builtin-integrations.stubs.ts
//
// Credential-only stub templates for providers not yet fully implemented.
// configSchema is real and stored on install; steps/outputs are empty pending implementation.
// Spread into BUILTIN_INTEGRATIONS via builtin-integrations.ts.

import type { IntegrationTemplate } from '../types/integration-types';

const NOW = Date.UTC(2026, 5, 22);

export const STUB_INTEGRATIONS: IntegrationTemplate[] = [
  // ── Threat Intelligence ──────────────────────────────────────────────────

  {
    id: 'recorded-future-lookup',
    schemaVersion: '1.0',
    version: '0.1.0',
    name: 'Recorded Future',
    description: 'Recorded Future threat intelligence enrichment. Save your API key to enable indicator lookups.',
    author: 'ThreatCaddy',
    icon: 'R',
    color: '#e11d48',
    category: 'enrichment',
    tags: ['threat-intel', 'stub'],
    triggers: [{ type: 'manual' }],
    configSchema: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, secret: true, placeholder: 'RF API key' },
    ],
    steps: [],
    outputs: [],
    requiredDomains: ['api.recordedfuture.com'],
    source: 'builtin',
    createdAt: NOW,
    updatedAt: NOW,
  },

  {
    id: 'threatconnect-lookup',
    schemaVersion: '1.0',
    version: '0.1.0',
    name: 'ThreatConnect',
    description: 'ThreatConnect threat intelligence platform. Configure credentials to enable indicator enrichment.',
    author: 'ThreatCaddy',
    icon: 'T',
    color: '#2563eb',
    category: 'threat-feed',
    tags: ['threat-intel', 'stub'],
    triggers: [{ type: 'manual' }],
    configSchema: [
      { key: 'baseUrl', label: 'Base URL', type: 'string', required: true, placeholder: 'https://app.threatconnect.com' },
      { key: 'accessId', label: 'Access ID', type: 'string', required: true, placeholder: 'TC access ID' },
      { key: 'secretKey', label: 'Secret Key', type: 'password', required: true, secret: true, placeholder: 'TC secret key' },
    ],
    steps: [],
    outputs: [],
    requiredDomains: [],
    source: 'builtin',
    createdAt: NOW,
    updatedAt: NOW,
  },

  {
    id: 'misp-lookup',
    schemaVersion: '1.0',
    version: '0.1.0',
    name: 'MISP',
    description: 'Malware Information Sharing Platform. Configure your MISP instance URL and API key.',
    author: 'ThreatCaddy',
    icon: 'M',
    color: '#7c3aed',
    category: 'threat-feed',
    tags: ['threat-intel', 'stub'],
    triggers: [{ type: 'manual' }],
    configSchema: [
      { key: 'baseUrl', label: 'MISP Instance URL', type: 'string', required: true, placeholder: 'https://misp.yourorg.com' },
      { key: 'apiKey', label: 'Auth Key', type: 'password', required: true, secret: true, placeholder: 'MISP auth key' },
      { key: 'verifySsl', label: 'Verify TLS', type: 'boolean', required: false, default: true },
    ],
    steps: [],
    outputs: [],
    requiredDomains: [],
    source: 'builtin',
    createdAt: NOW,
    updatedAt: NOW,
  },

  {
    id: 'opencti-lookup',
    schemaVersion: '1.0',
    version: '0.1.0',
    name: 'OpenCTI',
    description: 'OpenCTI threat intelligence platform. Configure your instance URL and API token.',
    author: 'ThreatCaddy',
    icon: 'O',
    color: '#0891b2',
    category: 'threat-feed',
    tags: ['threat-intel', 'stub'],
    triggers: [{ type: 'manual' }],
    configSchema: [
      { key: 'baseUrl', label: 'OpenCTI URL', type: 'string', required: true, placeholder: 'https://opencti.yourorg.com' },
      { key: 'apiToken', label: 'API Token', type: 'password', required: true, secret: true, placeholder: 'OpenCTI API token' },
    ],
    steps: [],
    outputs: [],
    requiredDomains: [],
    source: 'builtin',
    createdAt: NOW,
    updatedAt: NOW,
  },

  {
    id: 'taxii-stix-feed',
    schemaVersion: '1.0',
    version: '0.1.0',
    name: 'Generic TAXII / STIX Feed',
    description: 'Connect to any TAXII 2.x server to pull STIX 2.x threat intelligence.',
    author: 'ThreatCaddy',
    icon: 'T',
    color: '#d97706',
    category: 'threat-feed',
    tags: ['threat-intel', 'taxii', 'stix', 'stub'],
    triggers: [{ type: 'manual' }],
    configSchema: [
      { key: 'baseUrl', label: 'TAXII Server URL', type: 'string', required: true, placeholder: 'https://taxii.example.com/taxii/' },
      { key: 'username', label: 'Username', type: 'string', required: false, placeholder: 'Optional username' },
      { key: 'password', label: 'Password', type: 'password', required: false, secret: true, placeholder: 'Optional password' },
      { key: 'apiRoot', label: 'API Root', type: 'string', required: false, placeholder: 'default (leave blank for auto)' },
      { key: 'collectionId', label: 'Collection ID', type: 'string', required: false, placeholder: 'Leave blank for all' },
    ],
    steps: [],
    outputs: [],
    requiredDomains: [],
    source: 'builtin',
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── Malware Analysis ─────────────────────────────────────────────────────

  {
    id: 'hybrid-analysis-lookup',
    schemaVersion: '1.0',
    version: '0.1.0',
    name: 'Hybrid Analysis',
    description: 'Hybrid Analysis malware sandbox. Configure API key to enable hash and file lookups.',
    author: 'ThreatCaddy',
    icon: 'H',
    color: '#dc2626',
    category: 'enrichment',
    tags: ['malware-analysis', 'sandbox', 'stub'],
    triggers: [{ type: 'manual' }],
    configSchema: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, secret: true, placeholder: 'Hybrid Analysis API key' },
    ],
    steps: [],
    outputs: [],
    requiredDomains: ['www.hybrid-analysis.com'],
    source: 'builtin',
    createdAt: NOW,
    updatedAt: NOW,
  },

  {
    id: 'anyrun-lookup',
    schemaVersion: '1.0',
    version: '0.1.0',
    name: 'ANY.RUN',
    description: 'ANY.RUN interactive malware analysis sandbox. Configure API key to enable task and report lookups.',
    author: 'ThreatCaddy',
    icon: 'A',
    color: '#16a34a',
    category: 'enrichment',
    tags: ['malware-analysis', 'sandbox', 'stub'],
    triggers: [{ type: 'manual' }],
    configSchema: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, secret: true, placeholder: 'ANY.RUN API key' },
    ],
    steps: [],
    outputs: [],
    requiredDomains: ['api.any.run'],
    source: 'builtin',
    createdAt: NOW,
    updatedAt: NOW,
  },

  {
    id: 'joe-sandbox-lookup',
    schemaVersion: '1.0',
    version: '0.1.0',
    name: 'Joe Sandbox',
    description: 'Joe Sandbox malware analysis platform. Configure API key and URL to enable analysis lookups.',
    author: 'ThreatCaddy',
    icon: 'J',
    color: '#0369a1',
    category: 'enrichment',
    tags: ['malware-analysis', 'sandbox', 'stub'],
    triggers: [{ type: 'manual' }],
    configSchema: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, secret: true, placeholder: 'Joe Sandbox API key' },
      { key: 'baseUrl', label: 'Base URL', type: 'string', required: false, placeholder: 'https://jbxcloud.joesecurity.org (or on-prem URL)' },
    ],
    steps: [],
    outputs: [],
    requiredDomains: ['jbxcloud.joesecurity.org'],
    source: 'builtin',
    createdAt: NOW,
    updatedAt: NOW,
  },

  {
    id: 'intezer-lookup',
    schemaVersion: '1.0',
    version: '0.1.0',
    name: 'Intezer Analyze',
    description: 'Intezer malware genome analysis. Configure API key to enable file hash lookups and threat classification.',
    author: 'ThreatCaddy',
    icon: 'I',
    color: '#7c3aed',
    category: 'enrichment',
    tags: ['malware-analysis', 'stub'],
    triggers: [{ type: 'manual' }],
    configSchema: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, secret: true, placeholder: 'Intezer API key' },
    ],
    steps: [],
    outputs: [],
    requiredDomains: ['analyze.intezer.com'],
    source: 'builtin',
    createdAt: NOW,
    updatedAt: NOW,
  },

  {
    id: 'cape-sandbox-lookup',
    schemaVersion: '1.0',
    version: '0.1.0',
    name: 'CAPE Sandbox',
    description: 'CAPE malware analysis sandbox (open-source). Configure your instance URL and optional API key.',
    author: 'ThreatCaddy',
    icon: 'C',
    color: '#be123c',
    category: 'enrichment',
    tags: ['malware-analysis', 'sandbox', 'stub'],
    triggers: [{ type: 'manual' }],
    configSchema: [
      { key: 'baseUrl', label: 'CAPE Instance URL', type: 'string', required: true, placeholder: 'https://cape.yourorg.com' },
      { key: 'apiKey', label: 'API Token', type: 'password', required: false, secret: true, placeholder: 'Optional auth token' },
    ],
    steps: [],
    outputs: [],
    requiredDomains: [],
    source: 'builtin',
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── SIEM / SOAR ──────────────────────────────────────────────────────────

  {
    id: 'splunk-send-alert',
    schemaVersion: '1.0',
    version: '0.1.0',
    name: 'Splunk',
    description: 'Send events and alerts to Splunk HTTP Event Collector (HEC). Configure host and HEC token.',
    author: 'ThreatCaddy',
    icon: 'S',
    color: '#16a34a',
    category: 'siem-soar',
    tags: ['siem', 'stub'],
    triggers: [{ type: 'manual' }],
    configSchema: [
      { key: 'host', label: 'Splunk Host', type: 'string', required: true, placeholder: 'splunk.yourorg.com' },
      { key: 'port', label: 'HEC Port', type: 'number', required: false, default: 8088, placeholder: '8088' },
      { key: 'token', label: 'HEC Token', type: 'password', required: true, secret: true, placeholder: 'Splunk HEC token' },
      { key: 'index', label: 'Index', type: 'string', required: false, placeholder: 'main' },
      { key: 'useHttps', label: 'Use HTTPS', type: 'boolean', required: false, default: true },
    ],
    steps: [],
    outputs: [],
    requiredDomains: [],
    source: 'builtin',
    createdAt: NOW,
    updatedAt: NOW,
  },

  {
    id: 'elastic-siem-send',
    schemaVersion: '1.0',
    version: '0.1.0',
    name: 'Elastic SIEM',
    description: 'Send alerts and findings to Elasticsearch / Elastic Security. Configure connection details.',
    author: 'ThreatCaddy',
    icon: 'E',
    color: '#0ea5e9',
    category: 'siem-soar',
    tags: ['siem', 'elastic', 'stub'],
    triggers: [{ type: 'manual' }],
    configSchema: [
      {
        key: 'connectionType',
        label: 'Connection Type',
        type: 'select',
        required: true,
        default: 'cloud',
        options: [{ label: 'Elastic Cloud', value: 'cloud' }, { label: 'Self-hosted', value: 'selfhosted' }],
      },
      { key: 'cloudId', label: 'Cloud ID', type: 'string', required: false, placeholder: 'Cloud ID (Elastic Cloud only)' },
      { key: 'host', label: 'Host URL', type: 'string', required: false, placeholder: 'https://elastic.yourorg.com (self-hosted)' },
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, secret: true, placeholder: 'Base64-encoded api_id:api_key' },
      { key: 'index', label: 'Index', type: 'string', required: false, placeholder: 'threatcaddy-alerts' },
    ],
    steps: [],
    outputs: [],
    requiredDomains: [],
    source: 'builtin',
    createdAt: NOW,
    updatedAt: NOW,
  },

  {
    id: 'cortex-xsoar-send',
    schemaVersion: '1.0',
    version: '0.1.0',
    name: 'Cortex XSOAR',
    description: 'Create incidents and push findings to Cortex XSOAR / Palo Alto XSOAR.',
    author: 'ThreatCaddy',
    icon: 'X',
    color: '#ea580c',
    category: 'siem-soar',
    tags: ['soar', 'stub'],
    triggers: [{ type: 'manual' }],
    configSchema: [
      { key: 'baseUrl', label: 'XSOAR URL', type: 'string', required: true, placeholder: 'https://xsoar.yourorg.com' },
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, secret: true, placeholder: 'XSOAR API key' },
    ],
    steps: [],
    outputs: [],
    requiredDomains: [],
    source: 'builtin',
    createdAt: NOW,
    updatedAt: NOW,
  },

  {
    id: 'shuffle-trigger',
    schemaVersion: '1.0',
    version: '0.1.0',
    name: 'Shuffle',
    description: 'Trigger Shuffle SOAR workflows from ThreatCaddy events. Configure webhook URL.',
    author: 'ThreatCaddy',
    icon: 'S',
    color: '#7c3aed',
    category: 'siem-soar',
    tags: ['soar', 'stub'],
    triggers: [{ type: 'manual' }],
    configSchema: [
      { key: 'webhookUrl', label: 'Webhook URL', type: 'password', required: true, secret: true, placeholder: 'https://shuffler.io/api/v1/hooks/...' },
    ],
    steps: [],
    outputs: [],
    requiredDomains: ['shuffler.io'],
    source: 'builtin',
    createdAt: NOW,
    updatedAt: NOW,
  },

  {
    id: 'tines-trigger',
    schemaVersion: '1.0',
    version: '0.1.0',
    name: 'Tines',
    description: 'Trigger Tines automation stories from ThreatCaddy. Configure your Tines webhook URL.',
    author: 'ThreatCaddy',
    icon: 'T',
    color: '#059669',
    category: 'siem-soar',
    tags: ['soar', 'stub'],
    triggers: [{ type: 'manual' }],
    configSchema: [
      { key: 'webhookUrl', label: 'Webhook URL', type: 'password', required: true, secret: true, placeholder: 'https://yourorg.tines.com/webhook/...' },
    ],
    steps: [],
    outputs: [],
    requiredDomains: ['tines.com'],
    source: 'builtin',
    createdAt: NOW,
    updatedAt: NOW,
  },

  {
    id: 'sentinel-send',
    schemaVersion: '1.0',
    version: '0.1.0',
    name: 'Microsoft Sentinel',
    description: 'Send incidents and alerts to Microsoft Sentinel via the Log Analytics Data Collector API.',
    author: 'ThreatCaddy',
    icon: 'S',
    color: '#0078d4',
    category: 'siem-soar',
    tags: ['siem', 'microsoft', 'stub'],
    triggers: [{ type: 'manual' }],
    configSchema: [
      { key: 'workspaceId', label: 'Workspace ID', type: 'string', required: true, placeholder: 'Log Analytics workspace ID' },
      { key: 'sharedKey', label: 'Shared Key', type: 'password', required: true, secret: true, placeholder: 'Primary or secondary key' },
      { key: 'logType', label: 'Log Type Name', type: 'string', required: false, default: 'ThreatCaddyAlert', placeholder: 'ThreatCaddyAlert' },
    ],
    steps: [],
    outputs: [],
    requiredDomains: ['ods.opinsights.azure.com'],
    source: 'builtin',
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── Messaging / Notification ─────────────────────────────────────────────

  {
    id: 'teams-webhook-notify',
    schemaVersion: '1.0',
    version: '0.1.0',
    name: 'Microsoft Teams',
    description: 'Send alert notifications to a Microsoft Teams channel via Incoming Webhook.',
    author: 'ThreatCaddy',
    icon: 'T',
    color: '#5059c9',
    category: 'notification',
    tags: ['messaging', 'stub'],
    triggers: [{ type: 'manual' }],
    configSchema: [
      { key: 'webhookUrl', label: 'Incoming Webhook URL', type: 'password', required: true, secret: true, placeholder: 'https://yourorg.webhook.office.com/...' },
    ],
    steps: [],
    outputs: [],
    requiredDomains: ['webhook.office.com'],
    source: 'builtin',
    createdAt: NOW,
    updatedAt: NOW,
  },

  {
    id: 'discord-webhook-notify',
    schemaVersion: '1.0',
    version: '0.1.0',
    name: 'Discord',
    description: 'Send alert notifications to a Discord channel via webhook.',
    author: 'ThreatCaddy',
    icon: 'D',
    color: '#5865f2',
    category: 'notification',
    tags: ['messaging', 'stub'],
    triggers: [{ type: 'manual' }],
    configSchema: [
      { key: 'webhookUrl', label: 'Webhook URL', type: 'password', required: true, secret: true, placeholder: 'https://discord.com/api/webhooks/...' },
      { key: 'username', label: 'Bot Name', type: 'string', required: false, placeholder: 'ThreatCaddy' },
    ],
    steps: [],
    outputs: [],
    requiredDomains: ['discord.com'],
    source: 'builtin',
    createdAt: NOW,
    updatedAt: NOW,
  },

  {
    id: 'mattermost-webhook-notify',
    schemaVersion: '1.0',
    version: '0.1.0',
    name: 'Mattermost',
    description: 'Send alert notifications to a Mattermost channel via incoming webhook.',
    author: 'ThreatCaddy',
    icon: 'M',
    color: '#0058cc',
    category: 'notification',
    tags: ['messaging', 'stub'],
    triggers: [{ type: 'manual' }],
    configSchema: [
      { key: 'webhookUrl', label: 'Webhook URL', type: 'password', required: true, secret: true, placeholder: 'https://mattermost.yourorg.com/hooks/...' },
      { key: 'channel', label: 'Channel', type: 'string', required: false, placeholder: '#security-alerts' },
    ],
    steps: [],
    outputs: [],
    requiredDomains: [],
    source: 'builtin',
    createdAt: NOW,
    updatedAt: NOW,
  },

  {
    id: 'pagerduty-alert',
    schemaVersion: '1.0',
    version: '0.1.0',
    name: 'PagerDuty',
    description: 'Trigger PagerDuty incidents from ThreatCaddy findings. Configure Events API v2 integration key.',
    author: 'ThreatCaddy',
    icon: 'P',
    color: '#06d001',
    category: 'notification',
    tags: ['alerting', 'on-call', 'stub'],
    triggers: [{ type: 'manual' }],
    configSchema: [
      { key: 'routingKey', label: 'Integration Key (Events API v2)', type: 'password', required: true, secret: true, placeholder: '32-char integration key' },
      {
        key: 'severity',
        label: 'Default Severity',
        type: 'select',
        required: false,
        default: 'critical',
        options: [
          { label: 'Critical', value: 'critical' },
          { label: 'Error', value: 'error' },
          { label: 'Warning', value: 'warning' },
          { label: 'Info', value: 'info' },
        ],
      },
    ],
    steps: [],
    outputs: [],
    requiredDomains: ['events.pagerduty.com'],
    source: 'builtin',
    createdAt: NOW,
    updatedAt: NOW,
  },
];
