import type { AmbientAssistantCharacter } from '../../types';

/**
 * Ambient AI assistant mascots — a '90s software-buddy look (glossy volume,
 * specular highlights, chrome, cast shadows), built to be CUSTOMIZED rather
 * than picked from fixed presets. Each character exposes a set of slots
 * (face, glasses, hat, held item, colors…) with ~5 options each; the operator
 * clicks options in Settings → AI and the floating companion renders their
 * exact build.
 *
 * The SVG is assembled as a string (shared 3D toolkit below) and rendered via
 * an <svg> whose inner markup is injected — all generated by this module, no
 * user input, so the injection is safe. Animated parts carry `aa-part-*`
 * classes that the CSS in index.css drives (idle + a signature flourish while
 * the wrapper has `.is-waving`).
 */

// ---- 3D shading toolkit (string builders) -------------------------------
let gid = 0;
const uid = (p: string) => `${p}${gid++}`;

function sphere(light: string, base: string, dark: string) {
  const id = uid('sph');
  return {
    def: `<radialGradient id="${id}" cx="36%" cy="30%" r="72%"><stop offset="0%" stop-color="${light}"/><stop offset="45%" stop-color="${base}"/><stop offset="100%" stop-color="${dark}"/></radialGradient>`,
    fill: `url(#${id})`,
  };
}
function vgloss(top: string, bot: string) {
  const id = uid('vg');
  return { def: `<linearGradient id="${id}" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${top}"/><stop offset="1" stop-color="${bot}"/></linearGradient>`, fill: `url(#${id})` };
}
function chrome() {
  const id = uid('cr');
  return { def: `<linearGradient id="${id}" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#f4f7fb"/><stop offset="0.25" stop-color="#9fb0c4"/><stop offset="0.5" stop-color="#e8eef5"/><stop offset="0.75" stop-color="#6b7c93"/><stop offset="1" stop-color="#c3cedd"/></linearGradient>`, fill: `url(#${id})` };
}
function shade(hex: string, amt: number) {
  const n = parseInt(hex.slice(1), 16);
  let r = (n >> 16) + amt, g = ((n >> 8) & 255) + amt, b = (n & 255) + amt;
  r = Math.max(0, Math.min(255, r)); g = Math.max(0, Math.min(255, g)); b = Math.max(0, Math.min(255, b));
  return '#' + ((1 << 24) + (r << 16) + (g << 8) + b).toString(16).slice(1);
}
function eye(cx: number, cy: number, r: number, look = 0, cls = '') {
  const s = sphere('#ffffff', '#f0f3f8', '#cfd7e2');
  const pr = r * 0.5;
  return { def: s.def, svg: `<g class="${cls}"><circle cx="${cx}" cy="${cy}" r="${r}" fill="${s.fill}" stroke="#c2ccd8" stroke-width="0.6"/><circle cx="${cx + look}" cy="${cy + r * 0.15}" r="${pr}" fill="#1a1f2b"/><circle cx="${cx + look - pr * 0.35}" cy="${cy + r * 0.15 - pr * 0.4}" r="${pr * 0.34}" fill="#fff"/></g>` };
}

interface Ctx { defs: string[]; blur: string; blur2: string; }
function newCtx(): Ctx {
  const blur = uid('sft'), blur2 = uid('sft');
  return {
    defs: [`<filter id="${blur}" x="-40%" y="-40%" width="180%" height="180%"><feGaussianBlur stdDeviation="2.4"/></filter><filter id="${blur2}" x="-60%" y="-60%" width="220%" height="220%"><feGaussianBlur stdDeviation="4.5"/></filter>`],
    blur, blur2,
  };
}
const castShadow = (c: Ctx, cx: number, cy: number, rx: number, ry: number) => `<ellipse cx="${cx}" cy="${cy}" rx="${rx}" ry="${ry}" fill="#000" opacity="0.30" filter="url(#${c.blur2})"/>`;
const spec = (c: Ctx, cx: number, cy: number, rx: number, ry: number, op = 0.85) => `<ellipse cx="${cx}" cy="${cy}" rx="${rx}" ry="${ry}" fill="#ffffff" opacity="${op}" filter="url(#${c.blur})"/>`;

// ---- Customization schema types ----------------------------------------
export type MascotConfig = Record<string, string>;
export interface MascotOption { id: string; label: string; /** swatch colour for colour slots */ swatch?: string; }
export interface MascotSlot { id: string; label: string; type: 'color' | 'style'; options: MascotOption[]; }

interface Built { defs: string; inner: string; }

// ---- colour palettes shared by schema + builders ------------------------
const EDGAR_HAIR: Record<string, string> = { brown: '#5a3b26', black: '#2b2b32', blond: '#d9b25a', ginger: '#b5651d', silver: '#b8bcc4' };
const OUTFIT: Record<string, string> = { red: '#d64f45', blue: '#2f6fd0', green: '#39b06a', purple: '#7a53c0', charcoal: '#3a3f4a' };
const GOPHER_FUR: Record<string, [string, string, string]> = {
  tan: ['#d8a862', '#b98a52', '#7f5a2c'], chestnut: ['#c99a58', '#a97e46', '#6f4e26'],
  sandy: ['#e0b878', '#c49a5c', '#8a6636'], walnut: ['#b58a4f', '#946b34', '#5f421f'], ash: ['#b7a58c', '#8f7d64', '#5f5342'],
};
const CLIP_ACCENT: Record<string, string> = { charcoal: '#2f333c', red: '#c0453b', blue: '#2f6fd0', gold: '#e6b32e', purple: '#6b4ea0' };
const TEE: Record<string, string> = { red: '#d64f45', blue: '#2f6fd0', gold: '#e6b32e', green: '#39b06a', purple: '#8a5cd0' };

const colorOpts = (map: Record<string, string | string[]>): MascotOption[] =>
  Object.entries(map).map(([id, v]) => ({ id, label: id[0].toUpperCase() + id.slice(1), swatch: Array.isArray(v) ? v[1] : v }));

// ---- EDGAR --------------------------------------------------------------
function buildEdgar(cfg: MascotConfig): Built {
  const c = newCtx();
  const hair = EDGAR_HAIR[cfg.hair] || EDGAR_HAIR.brown;
  const oc = OUTFIT[cfg.outfit] || OUTFIT.red;
  const glasses = cfg.glasses || 'round';
  const hat = cfg.hat || 'none';
  const face = cfg.face || 'smile';
  const sk = ['#ffe0c2', '#f0b789', '#c98a5c'];
  const head = sphere(sk[0], sk[1], sk[2]); c.defs.push(head.def);
  const lens = sphere('#eaf3ff', '#cfe4ff', '#8fb6e6'); c.defs.push(lens.def);
  const collar = vgloss(shade(oc, 25), shade(oc, -25)); c.defs.push(collar.def);
  let g = '';
  g += castShadow(c, 100, 196, 52, 12);
  g += `<path d="M56 210 Q100 168 144 210 Z" fill="${collar.fill}"/><path d="M86 196 L100 214 L114 196 Z" fill="#eef3fa"/>`;
  g += `<path d="M100 194 L82 184 L82 204 Z" fill="${oc}"/><path d="M100 194 L118 184 L118 204 Z" fill="${oc}"/><circle cx="100" cy="194" r="5" fill="${shade(oc, -40)}"/>`;
  g += `<path d="M46 96 Q40 34 100 30 Q160 34 154 96 Q150 70 100 64 Q50 70 46 96 Z" fill="${hair}"/>`;
  g += `<circle cx="100" cy="98" r="58" fill="${head.fill}"/>`;
  g += `<circle cx="46" cy="100" r="10" fill="${sk[1]}"/><circle cx="154" cy="100" r="10" fill="${sk[1]}"/>`;
  g += `<path d="M56 78 Q70 40 118 44 Q150 48 150 78 Q120 58 92 60 Q68 62 56 78 Z" fill="${hair}"/>`;
  g += `<path class="aa-part-cowlick" d="M120 40 Q132 20 142 30 Q128 34 128 48 Z" fill="${hair}"/>`;
  g += spec(c, 80, 60, 16, 9, 0.3);
  const fr = '#2b2b32';
  const hasLens = glasses !== 'none';
  if (glasses === 'round') {
    g += `<circle cx="80" cy="100" r="22" fill="${lens.fill}"/><circle cx="120" cy="100" r="22" fill="${lens.fill}"/><circle cx="80" cy="100" r="22" fill="none" stroke="${fr}" stroke-width="5"/><circle cx="120" cy="100" r="22" fill="none" stroke="${fr}" stroke-width="5"/>`;
  } else if (glasses === 'square') {
    g += `<rect x="58" y="82" width="40" height="36" rx="7" fill="${lens.fill}"/><rect x="102" y="82" width="40" height="36" rx="7" fill="${lens.fill}"/><rect x="58" y="82" width="40" height="36" rx="7" fill="none" stroke="${fr}" stroke-width="5"/><rect x="102" y="82" width="40" height="36" rx="7" fill="none" stroke="${fr}" stroke-width="5"/>`;
  } else if (glasses === 'oval') {
    g += `<ellipse cx="80" cy="100" rx="23" ry="19" fill="${lens.fill}"/><ellipse cx="120" cy="100" rx="23" ry="19" fill="${lens.fill}"/><ellipse cx="80" cy="100" rx="23" ry="19" fill="none" stroke="${fr}" stroke-width="5"/><ellipse cx="120" cy="100" rx="23" ry="19" fill="none" stroke="${fr}" stroke-width="5"/>`;
  } else if (glasses === 'shades') {
    g += `<rect x="58" y="86" width="40" height="26" rx="10" fill="#20242c"/><rect x="102" y="86" width="40" height="26" rx="10" fill="#20242c"/><path d="M98 92 L102 92" stroke="#20242c" stroke-width="6"/><path d="M64 92 Q74 89 84 92" stroke="#7fa8d8" stroke-width="2.4" fill="none" opacity=".6"/>`;
  }
  if (hasLens) {
    g += `<path d="M68 88 Q78 84 88 90" stroke="#fff" stroke-width="3" fill="none" opacity="0.7" stroke-linecap="round"/><path d="M108 88 Q118 84 128 90" stroke="#fff" stroke-width="3" fill="none" opacity="0.7" stroke-linecap="round"/>`;
    g += `<path d="M96 100 Q100 96 104 100" stroke="${fr}" stroke-width="5" fill="none"/>`;
    g += `<circle cx="82" cy="103" r="4" fill="#25303f"/><circle cx="118" cy="103" r="4" fill="#25303f"/>`;
    // animated glint sweep (hidden until waving)
    g += `<rect class="aa-part-glint" x="60" y="84" width="7" height="30" rx="3" fill="#fff" opacity="0.85"/>`;
  } else {
    g += `<circle cx="82" cy="100" r="4.5" fill="#2b2b32"/><circle cx="118" cy="100" r="4.5" fill="#2b2b32"/>`;
  }
  const mouth = ({
    smile: 'M84 130 Q100 142 116 130', grin: 'M82 130 Q100 148 118 130', neutral: 'M86 134 L114 134',
    unsure: 'M86 136 Q100 130 114 136', delighted: 'M82 128 Q100 150 118 128',
  } as Record<string, string>)[face] || 'M84 130 Q100 142 116 130';
  g += `<path d="${mouth}" fill="none" stroke="#9c5a34" stroke-width="3" stroke-linecap="round"/>`;
  if (face === 'grin' || face === 'delighted') g += `<path d="${mouth} Z" fill="#8c4a2e" opacity="0.5"/>`;
  // hats
  if (hat === 'cap') g += `<path d="M48 66 Q100 26 152 66 L152 60 Q100 22 48 60 Z" fill="${oc}"/><path d="M150 62 L176 66 L150 74 Z" fill="${shade(oc, -20)}"/>`;
  else if (hat === 'beanie') g += `<path d="M46 70 Q100 20 154 70 Z" fill="${oc}"/><rect x="46" y="64" width="108" height="12" rx="6" fill="${shade(oc, -25)}"/><circle cx="100" cy="30" r="7" fill="${shade(oc, 30)}"/>`;
  else if (hat === 'phones') g += `<path d="M40 96 Q40 40 100 40 Q160 40 160 96" fill="none" stroke="#2f333c" stroke-width="8"/><rect x="30" y="90" width="20" height="30" rx="8" fill="#2f333c"/><rect x="150" y="90" width="20" height="30" rx="8" fill="#2f333c"/>`;
  else if (hat === 'grad') g += `<rect x="70" y="52" width="60" height="12" rx="2" fill="#2b2b32"/><path d="M56 52 L100 38 L144 52 L100 66 Z" fill="#2b2b32"/><line x1="144" y1="52" x2="150" y2="76" stroke="#e6b32e" stroke-width="2"/><circle cx="150" cy="78" r="4" fill="#e6b32e"/>`;
  return { defs: c.defs.join(''), inner: g };
}

// ---- GOPHER -------------------------------------------------------------
function buildGopher(cfg: MascotConfig): Built {
  const c = newCtx();
  const f = GOPHER_FUR[cfg.fur] || GOPHER_FUR.tan;
  const held = cfg.holding || 'flag';
  const hat = cfg.hat || 'none';
  const face = cfg.face || 'happy';
  const body = sphere(f[0], f[1], f[2]); c.defs.push(body.def);
  const belly = sphere('#f3e4c4', '#e6cfa8', '#cbb083'); c.defs.push(belly.def);
  const mound = vgloss('#7a5630', '#4a3016'); c.defs.push(mound.def);
  const ear = sphere(f[0], f[1], f[2]); c.defs.push(ear.def);
  let g = '';
  g += castShadow(c, 100, 204, 58, 12);
  // popping group (animates up out of the mound)
  let pop = '';
  pop += `<ellipse cx="100" cy="120" rx="46" ry="52" fill="${body.fill}"/>`;
  pop += `<ellipse cx="100" cy="134" rx="27" ry="32" fill="${belly.fill}"/>`;
  pop += `<circle cx="66" cy="82" r="15" fill="${ear.fill}"/><circle cx="134" cy="82" r="15" fill="${ear.fill}"/>`;
  pop += `<circle cx="66" cy="82" r="7" fill="${f[2]}"/><circle cx="134" cy="82" r="7" fill="${f[2]}"/>`;
  pop += spec(c, 78, 92, 16, 10, 0.28);
  const look = face === 'goofy' ? 2 : 0;
  const e1 = eye(84, 104, 10, look), e2 = eye(116, 104, 10, look); c.defs.push(e1.def, e2.def); pop += e1.svg + e2.svg;
  pop += `<ellipse cx="100" cy="122" rx="17" ry="13" fill="#f3e4c4"/>`;
  pop += `<ellipse cx="100" cy="118" rx="6" ry="4.5" fill="#6e4326"/>`;
  pop += `<rect x="92" y="126" width="16" height="18" rx="3" fill="#fff" stroke="#d8cbb0" stroke-width="1"/><line x1="100" y1="126" x2="100" y2="144" stroke="#d8cbb0" stroke-width="1"/>`;
  if (face === 'grin' || face === 'goofy') pop += `<path d="M86 130 Q100 150 114 130" fill="#7a4a2c"/>`;
  if (face === 'content') pop += `<path d="M78 100 Q84 96 90 100 M110 100 Q116 96 122 100" stroke="#2b2118" stroke-width="2.6" fill="none" stroke-linecap="round"/>`;
  pop += `<g stroke="#7a5630" stroke-width="1.4" stroke-linecap="round" opacity=".8"><line x1="70" y1="118" x2="88" y2="120"/><line x1="70" y1="126" x2="88" y2="126"/><line x1="130" y1="118" x2="112" y2="120"/><line x1="130" y1="126" x2="112" y2="126"/></g>`;
  // hat
  if (hat === 'hardhat') pop += `<path d="M64 74 Q100 44 136 74 Z" fill="#f2c14e"/><rect x="60" y="72" width="80" height="8" rx="4" fill="#e0a92e"/>`;
  else if (hat === 'cap') pop += `<path d="M66 76 Q100 52 134 76 L134 70 Q100 50 66 70 Z" fill="#2f6fd0"/><rect x="120" y="66" width="24" height="10" rx="3" fill="#2f6fd0"/>`;
  else if (hat === 'goggles') pop += `<g stroke="#3a3f4a" stroke-width="3" fill="none"><circle cx="84" cy="100" r="12"/><circle cx="116" cy="100" r="12"/><line x1="96" y1="100" x2="104" y2="100"/></g><circle cx="84" cy="100" r="12" fill="#6fd0ff" opacity=".35"/><circle cx="116" cy="100" r="12" fill="#6fd0ff" opacity=".35"/>`;
  else if (hat === 'beanie') pop += `<path d="M64 78 Q100 46 136 78 Z" fill="#c0453b"/><rect x="60" y="72" width="80" height="10" rx="5" fill="#9a3229"/><circle cx="100" cy="48" r="6" fill="#e0d5c0"/>`;
  // held item + paw
  pop += `<circle cx="150" cy="150" r="11" fill="${belly.fill}"/>`;
  if (held === 'flag') pop += `<g class="aa-part-flag"><line x1="150" y1="150" x2="150" y2="104" stroke="#7a5630" stroke-width="3"/><path d="M150 104 L182 112 L150 122 Z" fill="#e0574d"/></g>`;
  else if (held === 'wrench') pop += `<g transform="rotate(35 150 150)"><rect x="146" y="112" width="8" height="40" rx="3" fill="#9fb0c4"/><path d="M150 108 a10 10 0 1 0 0.1 0 M144 110 l6 6 6-6" fill="none" stroke="#9fb0c4" stroke-width="5"/></g>`;
  else if (held === 'magnifier') pop += `<g transform="rotate(20 150 150)"><circle cx="150" cy="120" r="13" fill="#bfe3ff" stroke="#8aa" stroke-width="4"/><rect x="147" y="132" width="6" height="20" rx="3" fill="#7a5630"/></g>`;
  else if (held === 'letter') pop += `<g transform="rotate(-10 150 148)"><rect x="136" y="132" width="30" height="22" rx="2" fill="#f5f0e4" stroke="#cbb083"/><path d="M136 134 L151 146 L166 134" fill="none" stroke="#cbb083" stroke-width="1.5"/></g>`;
  g += `<g class="aa-part-pop">${pop}</g>`;
  // mound (in front, static)
  g += `<path d="M28 176 Q100 148 172 176 L172 208 L28 208 Z" fill="${mound.fill}"/>`;
  g += `<ellipse cx="100" cy="176" rx="30" ry="8" fill="#3c2712"/>`;
  return { defs: c.defs.join(''), inner: g };
}

// ---- CLIP ---------------------------------------------------------------
function buildClip(cfg: MascotConfig): Built {
  const c = newCtx();
  const kind = cfg.type || 'paperclip';
  const acc = CLIP_ACCENT[cfg.accent] || CLIP_ACCENT.charcoal;
  const brow = cfg.brows || 'raised';
  const mouth = cfg.mouth || 'smile';
  const cr = chrome(); c.defs.push(cr.def);
  const bodyG = vgloss('#4a505c', '#20242c'); c.defs.push(bodyG.def);
  let g = '';
  g += castShadow(c, 100, 198, 40, 10);
  if (kind === 'binder') {
    g += `<g class="aa-part-arms" fill="none" stroke="${cr.fill}" stroke-width="6" stroke-linecap="round"><path d="M78 96 Q60 46 92 38"/><path d="M122 96 Q140 46 108 38"/></g>`;
    g += `<path d="M66 92 L134 92 L122 176 L78 176 Z" fill="${bodyG.fill}"/>`;
    g += `<path d="M66 92 L134 92 L131 112 L69 112 Z" fill="#565d6b" opacity=".8"/>`;
    g += spec(c, 80, 100, 10, 26, 0.25);
  } else if (kind === 'paperclip') {
    g += `<g class="aa-part-arms" fill="none" stroke="${cr.fill}" stroke-width="9" stroke-linecap="round"><path d="M84 60 L84 150 Q84 176 108 176 Q132 176 132 150 L132 78 Q132 58 114 58 Q98 58 98 76 L98 150"/></g>`;
    g += spec(c, 88, 90, 4, 40, 0.4);
  } else if (kind === 'rubber') {
    const rid = uid('rb'); c.defs.push(`<radialGradient id="${rid}" cx="40%" cy="35%" r="75%"><stop offset="0" stop-color="${shade(acc, 60)}"/><stop offset="60%" stop-color="${acc}"/><stop offset="100%" stop-color="${shade(acc, -50)}"/></radialGradient>`);
    g += `<g class="aa-part-arms"><ellipse cx="100" cy="120" rx="52" ry="60" fill="none" stroke="url(#${rid})" stroke-width="16"/><path d="M62 84 Q78 70 96 70" stroke="#fff" stroke-width="4" fill="none" opacity=".5" stroke-linecap="round"/></g>`;
  } else { // safety pin
    g += `<g class="aa-part-arms" fill="none" stroke="${cr.fill}" stroke-width="7" stroke-linecap="round"><path d="M78 70 L78 168 Q78 180 92 176 L128 150"/><circle cx="78" cy="66" r="12"/></g>`;
    g += `<path d="M118 138 L138 158 L128 166 Z" fill="${cr.fill}"/>`;
  }
  const cy = kind === 'binder' ? 128 : 120;
  const e1 = eye(86, cy - 2, 12, 0, 'aa-part-eye'), e2 = eye(114, cy - 2, 12, 0, 'aa-part-eye');
  c.defs.push(e1.def, e2.def); g += e1.svg + e2.svg;
  const brows = ({
    raised: `<path d="M74 ${cy - 18} Q86 ${cy - 24} 96 ${cy - 18}" stroke="${acc}" stroke-width="4" fill="none" stroke-linecap="round"/><path d="M104 ${cy - 18} Q114 ${cy - 24} 126 ${cy - 18}" stroke="${acc}" stroke-width="4" fill="none" stroke-linecap="round"/>`,
    angled: `<path d="M74 ${cy - 20} L96 ${cy - 15}" stroke="${acc}" stroke-width="4" stroke-linecap="round"/><path d="M126 ${cy - 20} L104 ${cy - 15}" stroke="${acc}" stroke-width="4" stroke-linecap="round"/>`,
    flat: `<path d="M74 ${cy - 18} L96 ${cy - 18}" stroke="${acc}" stroke-width="4" stroke-linecap="round"/><path d="M104 ${cy - 18} L126 ${cy - 18}" stroke="${acc}" stroke-width="4" stroke-linecap="round"/>`,
    worried: `<path d="M74 ${cy - 16} L96 ${cy - 20}" stroke="${acc}" stroke-width="4" stroke-linecap="round"/><path d="M126 ${cy - 16} L104 ${cy - 20}" stroke="${acc}" stroke-width="4" stroke-linecap="round"/>`,
    none: '',
  } as Record<string, string>)[brow] ?? '';
  g += brows;
  const m = ({
    smile: `M88 ${cy + 16} Q100 ${cy + 26} 112 ${cy + 16}`, grin: `M88 ${cy + 16} Q100 ${cy + 30} 112 ${cy + 16}`,
    flat: `M90 ${cy + 18} L110 ${cy + 18}`, smirk: `M90 ${cy + 16} Q104 ${cy + 24} 112 ${cy + 15}`,
    open: `M92 ${cy + 15} Q100 ${cy + 28} 108 ${cy + 15} Q100 ${cy + 20} 92 ${cy + 15}`,
  } as Record<string, string>)[mouth] || `M88 ${cy + 16} Q100 ${cy + 26} 112 ${cy + 16}`;
  const mFill = mouth === 'open' ? `fill="${shade(acc, -20)}"` : 'fill="none"';
  g += `<path d="${m}" ${mFill} stroke="${shade(acc, -10)}" stroke-width="3.4" stroke-linecap="round"/>`;
  return { defs: c.defs.join(''), inner: g };
}

// ---- WILSON -------------------------------------------------------------
function buildWilson(cfg: MascotConfig): Built {
  const c = newCtx();
  const tee = TEE[cfg.tee] || TEE.red;
  const face = cfg.face || 'smile';
  const topper = cfg.topper || 'none';
  const ball = sphere('#ffffff', '#eef1f5', '#c3ccd8'); c.defs.push(ball.def);
  const teeG = vgloss(shade(tee, 50), shade(tee, -30)); c.defs.push(teeG.def);
  let g = '';
  g += castShadow(c, 100, 206, 44, 10);
  g += `<path d="M88 178 L112 178 L106 206 L94 206 Z" fill="${teeG.fill}"/><ellipse cx="100" cy="176" rx="16" ry="5" fill="${shade(tee, 30)}"/>`;
  // ball group (animates: gentle wobble on the tee)
  let bg = '';
  bg += `<circle cx="100" cy="104" r="62" fill="${ball.fill}" stroke="#d3dae4" stroke-width="1.5"/>`;
  const dimId = uid('dmp'); c.defs.push(`<radialGradient id="${dimId}" cx="60%" cy="65%" r="60%"><stop offset="0" stop-color="#ffffff"/><stop offset="100%" stop-color="#d5dbe4"/></radialGradient>`);
  for (let r = 0; r < 5; r++) for (let col = 0; col < 6; col++) {
    const x = 64 + col * 15 + (r % 2 ? 7 : 0), y = 64 + r * 15;
    if (Math.hypot(x - 100, y - 104) < 52) bg += `<circle cx="${x}" cy="${y}" r="3.4" fill="url(#${dimId})"/>`;
  }
  bg += spec(c, 76, 78, 20, 13, 0.9) + spec(c, 72, 74, 9, 6, 0.95);
  const eyeOne = (x: number, y: number, r: number) => `<circle cx="${x}" cy="${y}" r="${r}" fill="#1a1f2b"/><circle cx="${x - r * 0.3}" cy="${y - r * 0.35}" r="${r * 0.34}" fill="#fff"/>`;
  if (face === 'cool') {
    bg += `<rect x="62" y="92" width="76" height="20" rx="9" fill="#20242c"/><rect x="62" y="92" width="34" height="20" rx="9" fill="#2a2f38"/><rect x="104" y="92" width="34" height="20" rx="9" fill="#2a2f38"/><path d="M66 97 Q76 94 86 97" stroke="#7fa8d8" stroke-width="2" fill="none" opacity=".6"/>`;
    bg += `<path d="M84 128 Q100 138 116 128" stroke="#3a3f4a" stroke-width="3.4" fill="none" stroke-linecap="round"/>`;
  } else {
    if (face === 'wink') bg += eyeOne(80, 100, 8) + `<path d="M112 100 Q120 96 128 100" stroke="#1a1f2b" stroke-width="3.4" fill="none" stroke-linecap="round"/>`;
    else bg += eyeOne(80, 100, 8) + eyeOne(120, 100, 8);
    if (face === 'grin') bg += `<path d="M78 122 Q100 146 122 122 Q100 132 78 122 Z" fill="#a23b34"/><path d="M80 123 L120 123" stroke="#fff" stroke-width="4"/>`;
    else if (face === 'tongue') bg += `<path d="M80 122 Q100 140 120 122" stroke="#2b2b32" stroke-width="3.4" fill="none"/><ellipse cx="100" cy="134" rx="8" ry="7" fill="#e0574d"/>`;
    else bg += `<path d="M82 124 Q100 140 118 124" stroke="#2b2b32" stroke-width="3.4" fill="none" stroke-linecap="round"/>`;
  }
  // toppers
  if (topper === 'visor') bg += `<path d="M56 84 Q100 66 144 84 L144 76 Q100 58 56 76 Z" fill="${shade(tee, 10)}"/><rect x="60" y="82" width="80" height="8" rx="4" fill="${shade(tee, -10)}"/>`;
  else if (topper === 'cap') bg += `<path d="M52 74 Q100 34 148 74 L148 68 Q100 30 52 68 Z" fill="${tee}"/><path d="M146 70 L172 74 L146 82 Z" fill="${shade(tee, -20)}"/>`;
  else if (topper === 'tophat') bg += `<rect x="72" y="26 " width="56" height="34" rx="3" fill="#2b2b32"/><rect x="58" y="58" width="84" height="10" rx="4" fill="#2b2b32"/><rect x="72" y="48" width="56" height="7" fill="${tee}"/>`;
  else if (topper === 'crown') bg += `<path d="M64 60 L64 40 L80 52 L100 32 L120 52 L136 40 L136 60 Z" fill="#e6b32e" stroke="#c9922a" stroke-width="1.5"/><circle cx="100" cy="44" r="3.5" fill="#e0574d"/>`;
  g += `<g class="aa-part-ball">${bg}</g>`;
  return { defs: c.defs.join(''), inner: g };
}

// ---- registry -----------------------------------------------------------
export interface MascotDefinition {
  id: AmbientAssistantCharacter;
  name: string;
  tagline: string;
  accent: string;
  tips: string[];
  slots: MascotSlot[];
  defaults: MascotConfig;
  build: (cfg: MascotConfig) => Built;
}

export const AMBIENT_MASCOTS: MascotDefinition[] = [
  {
    id: 'edgar', name: 'Edgar', accent: '#3f6f9f',
    tagline: 'The resident nerd. Reads the footnotes so you don’t have to.',
    tips: [
      'Tip: press ⌘K to jump straight to any investigation.',
      'Actually, that IOC looks like a defanged URL — want me to re-fang it?',
      'A well-labeled timeline event is a happy timeline event.',
      'Did you know? Every product can be templatized from a real docx.',
    ],
    slots: [
      { id: 'glasses', label: 'Glasses', type: 'style', options: [
        { id: 'round', label: 'Round' }, { id: 'square', label: 'Square' }, { id: 'oval', label: 'Oval' }, { id: 'shades', label: 'Shades' }, { id: 'none', label: 'None' } ] },
      { id: 'face', label: 'Face', type: 'style', options: [
        { id: 'smile', label: 'Smile' }, { id: 'grin', label: 'Grin' }, { id: 'neutral', label: 'Neutral' }, { id: 'unsure', label: 'Unsure' }, { id: 'delighted', label: 'Delighted' } ] },
      { id: 'hat', label: 'Hat', type: 'style', options: [
        { id: 'none', label: 'None' }, { id: 'cap', label: 'Cap' }, { id: 'beanie', label: 'Beanie' }, { id: 'phones', label: 'Headphones' }, { id: 'grad', label: 'Grad cap' } ] },
      { id: 'hair', label: 'Hair', type: 'color', options: colorOpts(EDGAR_HAIR) },
      { id: 'outfit', label: 'Bow tie', type: 'color', options: colorOpts(OUTFIT) },
    ],
    defaults: { glasses: 'round', face: 'smile', hat: 'none', hair: 'brown', outfit: 'red' },
    build: buildEdgar,
  },
  {
    id: 'gopher', name: 'Gopher', accent: '#b98a52',
    tagline: 'Your gopher — pops up to fetch whatever you need.',
    tips: [
      'Say the word and I’ll fetch the latest threat feed.',
      'Need that evidence item? I’ll dig it up.',
      'Burrowing through your notes… found three untagged ones.',
      'I fetched you a fresh scan job. You’re welcome.',
    ],
    slots: [
      { id: 'holding', label: 'Holding', type: 'style', options: [
        { id: 'flag', label: 'Flag' }, { id: 'wrench', label: 'Wrench' }, { id: 'magnifier', label: 'Magnifier' }, { id: 'letter', label: 'Letter' }, { id: 'none', label: 'Nothing' } ] },
      { id: 'hat', label: 'Hat', type: 'style', options: [
        { id: 'none', label: 'None' }, { id: 'hardhat', label: 'Hard hat' }, { id: 'cap', label: 'Cap' }, { id: 'goggles', label: 'Goggles' }, { id: 'beanie', label: 'Beanie' } ] },
      { id: 'face', label: 'Face', type: 'style', options: [
        { id: 'happy', label: 'Happy' }, { id: 'grin', label: 'Grin' }, { id: 'goofy', label: 'Goofy' }, { id: 'content', label: 'Content' } ] },
      { id: 'fur', label: 'Fur', type: 'color', options: colorOpts(GOPHER_FUR) },
    ],
    defaults: { holding: 'flag', hat: 'none', face: 'happy', fur: 'tan' },
    build: buildGopher,
  },
  {
    id: 'clip', name: 'Clip', accent: '#565d6b',
    tagline: 'A clip with opinions. It looks like you’re writing a report!',
    tips: [
      'It looks like you’re writing a report. Want a template?',
      'Two clips are better than one. So is a second reviewer.',
      'I hold things together. Like your draft checkpoints.',
      'Pinned it. Metaphorically and literally.',
    ],
    slots: [
      { id: 'type', label: 'Style', type: 'style', options: [
        { id: 'paperclip', label: 'Paperclip' }, { id: 'binder', label: 'Binder clip' }, { id: 'rubber', label: 'Rubber band' }, { id: 'safety', label: 'Safety pin' } ] },
      { id: 'brows', label: 'Brows', type: 'style', options: [
        { id: 'raised', label: 'Raised' }, { id: 'angled', label: 'Angled' }, { id: 'flat', label: 'Flat' }, { id: 'worried', label: 'Worried' }, { id: 'none', label: 'None' } ] },
      { id: 'mouth', label: 'Mouth', type: 'style', options: [
        { id: 'smile', label: 'Smile' }, { id: 'grin', label: 'Grin' }, { id: 'flat', label: 'Flat' }, { id: 'smirk', label: 'Smirk' }, { id: 'open', label: 'Open' } ] },
      { id: 'accent', label: 'Accent', type: 'color', options: colorOpts(CLIP_ACCENT) },
    ],
    defaults: { type: 'paperclip', brows: 'raised', mouth: 'smile', accent: 'charcoal' },
    build: buildClip,
  },
  {
    id: 'wilson', name: 'Wilson', accent: '#d64f45',
    tagline: 'A golf ball who believes in you. Fits the Caddy, naturally.',
    tips: [
      'You’ve got this. I’m just here for moral support.',
      'Nice drive on that investigation. Keep going.',
      'Fore! ...sorry, force of habit. Carry on, Caddy.',
      'Stay on the fairway. Or, you know, close the ticket.',
    ],
    slots: [
      { id: 'face', label: 'Face', type: 'style', options: [
        { id: 'smile', label: 'Smile' }, { id: 'grin', label: 'Grin' }, { id: 'cool', label: 'Shades' }, { id: 'wink', label: 'Wink' }, { id: 'tongue', label: 'Tongue' } ] },
      { id: 'topper', label: 'Topper', type: 'style', options: [
        { id: 'none', label: 'None' }, { id: 'visor', label: 'Visor' }, { id: 'cap', label: 'Cap' }, { id: 'tophat', label: 'Top hat' }, { id: 'crown', label: 'Crown' } ] },
      { id: 'tee', label: 'Tee', type: 'color', options: colorOpts(TEE) },
    ],
    defaults: { face: 'smile', topper: 'none', tee: 'red' },
    build: buildWilson,
  },
];

export function getMascot(id: AmbientAssistantCharacter | undefined): MascotDefinition {
  return AMBIENT_MASCOTS.find((m) => m.id === id) ?? AMBIENT_MASCOTS[0];
}

/** Fills any missing slot in a stored config with the character's default. */
export function resolveConfig(id: AmbientAssistantCharacter | undefined, config: MascotConfig | undefined): MascotConfig {
  const def = getMascot(id);
  return { ...def.defaults, ...(config || {}) };
}

// ---- React component ----------------------------------------------------
export interface MascotProps {
  character: AmbientAssistantCharacter;
  config?: MascotConfig;
  size?: number;
  waving?: boolean;
  className?: string;
  title?: string;
}

export function Mascot({ character, config, size = 64, waving, className = '', title }: MascotProps) {
  const def = getMascot(character);
  const cfg = resolveConfig(character, config);
  const { defs, inner } = def.build(cfg);
  const html = `<defs>${defs}</defs>${inner}`;
  return (
    <svg
      className={`aa-mascot aa-${character} ${className}${waving ? ' is-waving' : ''}`}
      viewBox="0 0 200 220"
      width={size}
      height={Math.round(size * 1.1)}
      role="img"
      aria-label={title || def.name}
      xmlns="http://www.w3.org/2000/svg"
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}
